version: 43.0.9
pageUuid: 8f51acc4-9a61-11ec-9a21-ef8b44ac8f17
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
  rootScreen: null
  version: 2.88.13
  markdownLinkBehavior: auto
