version: 43.0.9
pageUuid: 95e91fa8-d1c1-11ec-be27-df4254d73c74
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  queryStatusVisibility: true
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 3.4.2
  markdownLinkBehavior: never
