version: 43.0.9
pageUuid: 21568026-142e-11ee-868b-8bab9f9d920c
appTemplate:
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.123.1
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
