id: AddMetricToCaherConfigModal
type: widget
subtype: ModalWidget
template:
  ordered:
    - opened: false
    - modalOverflowType: scroll
    - onModalClose: ''
    - modalHeightType: fixed
    - tooltipText: ''
    - modalHeight: '250'
    - onModalOpen: ''
    - modalWidth: 30%
    - closeOnOutsideClick: false
    - loading: ''
    - disabled: ''
    - buttonText: Add metric
style:
  ordered: []
position2:
  position2:
    container: CacherConfigForm
    row: 7.200000000000001
    col: 6
    height: 1
    width: 3
createdAt: 2023-02-17T11:21:13.440Z
