id: argovisorConfigIndicator
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: left
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: >-
        {{!isArgovisorConfigInvalid.value ? "Config is Valid for upsert ✅" :
        "Config is Invalid for upsert⛔ ⛔"}}
    - _disclosedFields:
        array: []
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: ArgohConfigForm
    rowGroup: footer
    col: 5
    height: 0.6
    width: 2
createdAt: 2023-04-23T13:04:53.686Z
