id: CacherJsonConfig
type: widget
subtype: JSONEditorWidget
template:
  ordered:
    - formDataKey: '{{ self.id }}'
    - value: >+
        {{
        GetJobsConfig.data.jobs.filter(x=>x.name=="cacher")[0]?.config?.metrics
        ?? [] }}

    - valid: true
    - events: []
style:
  ordered: []
position2:
  position2:
    container: CacherConfigForm
    row: 0.3999999999999999
    col: 1
    height: 8
    width: 4
createdAt: 2023-02-15T12:42:39.200Z
