id: CacherDefaultRangeJsonConfig
type: widget
subtype: JSONEditorWidget
template:
  ordered:
    - formDataKey: '{{ self.id }}'
    - value: >+
        {{ GetJobsConfig.data.jobs.filter(x=>x.name=="cacher")[0]?.config?.range
        ?? {"month": [-12, 0], "quarter": [-5, 0], "fyear": [-2, 0]} }}

    - valid: true
    - events: []
    - maintainSpaceWhenHidden: false
    - showInEditor: false
style:
  ordered: []
position2:
  position2:
    container: CacherConfigForm
    row: 2.4000000000000004
    col: 6
    height: 3.8
    width: 4
createdAt: 2023-02-18T09:55:19.622Z
