id: db2graphSpecificConfigPath
type: widget
subtype: TextInputWidget2
template:
  ordered:
    - spellCheck: false
    - readOnly: false
    - iconAfter: ''
    - showCharacterCount: false
    - autoComplete: false
    - maxLength: null
    - hidden: false
    - customValidation: ''
    - patternType: ''
    - hideValidationMessage: false
    - textBefore: ''
    - validationMessage: ''
    - textAfter: ''
    - showInEditor: false
    - _defaultValue: ''
    - showClear: false
    - pattern: ''
    - tooltipText: ''
    - labelAlign: left
    - formDataKey: '{{ self.id }}'
    - value: >-
        {{GetChosenDB2GraphConfig.data.jobs[0]?.config?.specific_config_path ??
        `/schemas/${TenantCodeName.value}/db2graph/config.yaml`}}
    - style:
        ordered:
          - background: >-
              {{GetChosenDB2GraphConfig.data.jobs[0]?.config?.specific_config_path
              == db2graphSpecificConfigPath.value ? "#FFFFFF" : "#696969"}}
    - labelCaption: ''
    - labelWidth: '33'
    - autoFill: ''
    - placeholder: /schemas/<client>/db2graph/config.yaml
    - _disclosedFields:
        array: []
    - label: Specific config path
    - _validate: false
    - labelWidthUnit: '%'
    - invalid: false
    - iconBefore: ''
    - minLength: null
    - inputTooltip: ''
    - events:
        ordered: []
    - autoCapitalize: none
    - loading: false
    - disabled: false
    - labelPosition: left
    - labelWrap: false
    - maintainSpaceWhenHidden: false
    - required: false
style:
  ordered: []
position2:
  position2:
    container: DB2GraphConfig
    row: 0.9999999999999996
    height: 1
    width: 4
createdAt: 2022-01-27T10:22:30.754Z
