id: DefaultRangeConfigText
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: left
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: '**Default range config:**'
    - _disclosedFields:
        array: []
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: CacherConfigForm
    row: 1.8
    col: 6
    height: 0.6
    width: 3
createdAt: 2023-02-18T09:57:04.779Z
