id: hermesConfigIndicator
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: left
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: >-
        {{!isHermesConfigInvalid.value ? "Config is Valid for upsert ✅" :
        "Config is Invalid for upsert⛔ ⛔"}}
    - _disclosedFields:
        array: []
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: HermesConfigForm
    rowGroup: footer
    row: 0.19999999999999996
    col: 7
    height: 0.6
    width: 3
createdAt: 2023-04-24T07:09:02.919Z
