id: isCacherConfigInvalid
type: function
subtype: Function
template:
  ordered:
    - funcBody: >-
        let isWorkersAmountInvalid = {{ CacherAsyncWorkers.value <= 0 }}

        let isCacherCacherJsonConfigInvalid = {{ CacherJsonConfig.value === {}
        || CacherJsonConfig.value === undefined}}


        return {{isUnAuthorizedForUpsert.value}} ||
        {{isJobConfigDataInvalid.value}} || isWorkersAmountInvalid ||
        isCacherCacherJsonConfigInvalid
    - value: ''
createdAt: 2023-04-23T14:26:14.732Z
folder: upsertValidations
