id: isHermesConfigInvalid
type: function
subtype: Function
template:
  ordered:
    - funcBody: >-
        let isScheduleInvalid = {{HermesSchedule.value === "" ||
        HermesSchedule.value === undefined}}


        return {{isUnAuthorizedForUpsert.value}} ||
        {{isJobConfigDataInvalid.value}} || isScheduleInvalid
    - value: ''
createdAt: 2023-04-24T07:09:26.659Z
folder: upsertValidations
