id: isJobConfigDataInvalid
type: function
subtype: Function
template:
  ordered:
    - funcBody: >-
        return {{ GetJobsConfig.data === undefined || GetJobsConfig.data === {}
        }}
    - value: ''
createdAt: 2023-04-23T13:18:20.126Z
folder: upsertValidations
