id: isMetricTesterConfigInvalid
type: function
subtype: Function
template:
  ordered:
    - funcBody: >-
        let isCronInvalid = {{ MetricTesterSchedule.value === "" ||
        MetricTesterSchedule.value === undefined }}

        let isNumberofThreadsInvalid = {{ MetricTesterNumThreads.value <= 0 }}



        return {{ isUnAuthorizedForUpsert.value }} || {{
        isJobConfigDataInvalid.value }} || isCronInvalid ||
        isNumberofThreadsInvalid
    - value: ''
createdAt: 2023-04-24T07:43:52.261Z
folder: upsertValidations
