id: isTailorConfigInvalid
type: function
subtype: Function
template:
  ordered:
    - funcBody: >-
        let isTailorConfigPathInvalid = {{ TailorConfigPath.value === "" ||
        TailorConfigPath.value === undefined }}

        let isTailorSpecificConfigPathInvalid = {{
        TailorSpecificConfigPath.value === "" || TailorSpecificConfigPath.value
        === undefined }}


        return isTailorSpecificConfigPathInvalid || isTailorConfigPathInvalid ||
        {{ isUnAuthorizedForUpsert.value }} || {{ isJobConfigDataInvalid.value
        }}
    - value: ''
createdAt: 2023-04-20T13:53:09.196Z
folder: upsertValidations
