id: isUseratorConfigInvalid
type: function
subtype: Function
template:
  ordered:
    - funcBody: >-
        let isTenantConfigPathInvalid = {{ UseratorTenantConfigPath.value === ""
        || UseratorTenantConfigPath.value === undefined }}


        let isScheduleInvalid = {{ UseratorSchedule.value === "" ||
        UseratorSchedule.value === undefined }} 


        let isSchemaRepoInvalid = {{ useratorSchemaRepo.value === "" ||
        useratorSchemaRepo.value === undefined }}
          
        let isSalesforceDBInvalid = {{ useratorSalesforceSchema.value === "" ||
        useratorSalesforceSchema.value === undefined }}
          
        return {{ isUnAuthorizedForUpsert.value }} || {{
        isJobConfigDataInvalid.value }} || isTenantConfigPathInvalid ||
        isScheduleInvalid || isSchemaRepoInvalid || isSalesforceDBInvalid
    - value: ''
createdAt: 2023-04-23T14:34:50.483Z
folder: upsertValidations
