id: MetricTesterConfigForm
type: widget
subtype: FormWidget2
template:
  ordered:
    - disableSubmit: '{{isMetricTesterConfigInvalid.value}}'
    - heightType: auto
    - resetAfterSubmit: ''
    - submitting: false
    - hidden: false
    - data:
        object: {}
    - showHeader: true
    - hoistFetching: true
    - _hasSubmitEvents: false
    - initialData: ''
    - showInEditor: false
    - tooltipText: Metric Tester
    - _disclosedFields:
        array:
          - tooltipText
    - invalid: false
    - showFooter: true
    - events:
        - ordered:
            - event: submit
            - type: datasource
            - method: trigger
            - pluginId: UpsertMetricTesterConfig
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
            - enabled: '{{IsStaffRole.data && GetJobsConfig.data != undefined}}'
    - loading: false
    - overflowType: scroll
    - disabled: false
    - requireValidation: true
    - maintainSpaceWhenHidden: false
    - showBody: true
style:
  ordered: []
position2:
  position2:
    container: TenantSettingsTabs
    subcontainer: '6'
    row: 0.8000000000000003
    height: 6
    width: 12
createdAt: 2022-01-06T18:30:28.170Z
