id: MetricTesterConfigJson
type: widget
subtype: JSONEditorWidget
template:
  ordered:
    - formDataKey: '{{ self.id }}'
    - value: >+
        {{GetJobsConfig.data.jobs.filter(x=>x.name=="metric-tester")[0]?.config?.metric_groups
        ?? {
          "critical": {
            "append_metrics": []
          },
          "critical_finance": {
            "append_metrics": []
          },
          "documentation": {
            "append_metrics": []
          },
          "dont_run": {
            "append_metrics": []
          }
        }}}

    - valid: true
    - events: []
style:
  ordered: []
position2:
  position2:
    container: MetricTesterConfigForm
    row: 1.4
    col: 1
    height: 8
    width: 4
createdAt: 2022-06-01T14:59:32.275Z
