id: metricTesterConfigIndicator
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: left
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: >-
        {{!isMetricTesterConfigInvalid.value ? "Config is Valid for upsert ✅" :
        "Config is Invalid for upsert⛔ ⛔"}}
    - _disclosedFields:
        array: []
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: MetricTesterConfigForm
    rowGroup: footer
    row: 0.20000000000000107
    col: 8
    height: 0.6
    width: 2
createdAt: 2023-04-25T05:57:58.736Z
