id: productionTokenButton
type: widget
subtype: ButtonWidget2
template:
  ordered:
    - horizontalAlign: stretch
    - clickable: false
    - iconAfter: ''
    - submitTargetId: ''
    - hidden: false
    - text: Production
    - showInEditor: false
    - tooltipText: ''
    - style:
        ordered:
          - background: '#c74438ff'
    - _disclosedFields:
        array: []
    - styleVariant: solid
    - submit: false
    - iconBefore: ''
    - events:
        - ordered:
            - event: click
            - type: util
            - method: openUrl
            - pluginId: ''
            - params:
                ordered:
                  - url: >-
                      https://auth.sightfull.com/authorize?client_id=SGmy3teE0hUrZc6Cl1Kkhk9rASjkGe4q&response_type=token&response_mode=fragment&audience=https://api.sightfull.com/&scope=openid%20profile%20email&redirect_uri={{urlparams.href.split('/').slice(0,5).join('/')}}%3F_releaseVersion={{urlparams._releaseVersion}}
                  - options:
                      ordered:
                        - forceReload: false
                        - newTab: false
            - waitType: debounce
            - waitMs: '0'
    - loading: false
    - loaderPosition: auto
    - disabled: ''
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: tabs
    subcontainer: '0'
    row: 2
    col: 8
    height: 1
    width: 1
createdAt: 2021-10-27T20:18:06.072Z
