id: settingsTabs
type: widget
subtype: TabsWidget2
template:
  ordered:
    - _disabledByIndex:
        - ''
        - ''
        - ''
    - _values:
        - Tab 1
        - Tab 2
        - Tab 3
    - iconByIndex:
        array: []
    - values:
        array: []
    - alignment: left
    - _iconByIndex:
        - ''
        - ''
        - ''
    - hidden: false
    - data:
        array: []
    - targetContainerId: TenantSettingsTabs
    - selectedItem: null
    - showInEditor: false
    - _defaultValue: null
    - navigateContainer: true
    - value: '{{ self.values[0] }}'
    - hiddenByIndex:
        array: []
    - _hiddenByIndex:
        - ''
        - ''
        - ''
    - _disclosedFields:
        array: []
    - _hasMigratedNestedItems: true
    - itemMode: static
    - selectedIndex: null
    - _tooltipByIndex:
        - ''
        - ''
        - ''
    - tooltipByIndex:
        array: []
    - selectedLabel: ''
    - events:
        ordered: []
    - _ids:
        - 07ca4
        - 8a08d
        - 82ad5
    - iconPositionByIndex:
        array: []
    - _iconPositionByIndex:
        - ''
        - ''
        - ''
    - disabled: ''
    - linePosition: bottom
    - _labels:
        - ''
        - ''
        - ''
    - disabledByIndex:
        array: []
    - maintainSpaceWhenHidden: false
    - labels:
        array: []
style:
  ordered: []
position2:
  position2:
    container: TenantSettingsTabs
    rowGroup: header
    height: 0.8
    width: 12
createdAt: 2022-06-01T11:08:19.742Z
