id: SumbitDb2graphConfig
type: widget
subtype: ButtonWidget2
template:
  ordered:
    - horizontalAlign: stretch
    - clickable: false
    - iconAfter: ''
    - submitTargetId: DB2GraphConfig
    - hidden: false
    - text: Submit
    - showInEditor: false
    - tooltipText: ''
    - _disclosedFields:
        array: []
    - submit: true
    - iconBefore: ''
    - events:
        ordered: []
    - loading: false
    - loaderPosition: auto
    - disabled: false
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: DB2GraphConfig
    rowGroup: footer
    row: 1
    col: 8
    height: 1
    width: 4
createdAt: 2022-01-27T10:13:43.953Z
