id: TailorConfigPath
type: widget
subtype: TextInputWidget2
template:
  ordered:
    - spellCheck: false
    - readOnly: false
    - iconAfter: ''
    - showCharacterCount: false
    - autoComplete: false
    - maxLength: null
    - hidden: false
    - customValidation: ''
    - patternType: ''
    - hideValidationMessage: false
    - textBefore: ''
    - validationMessage: ''
    - textAfter: ''
    - showInEditor: false
    - _defaultValue: ''
    - showClear: false
    - pattern: ''
    - tooltipText: ''
    - labelAlign: left
    - formDataKey: '{{ self.id }}'
    - value: >-
        {{GetJobsConfig.data.jobs.filter(x=>x.name=="Tailor")[0]?.config?.config_path
        ?? `/schemas/default/tailor-op`}}
    - style:
        ordered:
          - background: >-
              {{GetJobsConfig.data.jobs.filter(x=>x.name=="Tailor")[0]?.config?.config_path
              == TailorConfigPath.value ? "#FFFFFF" : "#696969"}}
    - labelCaption: ''
    - labelWidth: '33'
    - autoFill: ''
    - placeholder: /schemas/default/tailor-op
    - _disclosedFields:
        array: []
    - label: Default config path
    - _validate: false
    - labelWidthUnit: '%'
    - invalid: false
    - iconBefore: ''
    - minLength: null
    - inputTooltip: ''
    - events:
        ordered: []
    - autoCapitalize: none
    - loading: false
    - disabled: false
    - labelPosition: left
    - labelWrap: false
    - maintainSpaceWhenHidden: false
    - required: false
style:
  ordered: []
position2:
  position2:
    container: TailorConfigForm
    height: 1
    width: 4
createdAt: 2021-11-11T08:30:58.757Z
