id: TailorConfigForm
type: widget
subtype: FormWidget2
template:
  ordered:
    - disableSubmit: '{{!IsStaffRole.data || isTailorConfigInvalid.value }}'
    - heightType: fixed
    - resetAfterSubmit: true
    - submitting: false
    - hidden: null
    - data:
        object: {}
    - showHeader: false
    - hoistFetching: true
    - initialData: null
    - showInEditor: null
    - tooltipText: ''
    - _disclosedFields:
        array: []
    - invalid: false
    - showFooter: true
    - events:
        - ordered:
            - event: submit
            - type: datasource
            - method: trigger
            - pluginId: UpsertTailorConfig
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
            - enabled: '{{IsStaffRole.data && GetJobsConfig.data != undefined}}'
    - loading: false
    - overflowType: hidden
    - disabled: '{{!IsStaffRole.data}}'
    - requireValidation: true
    - maintainSpaceWhenHidden: null
    - showBody: true
style:
  ordered: []
position2:
  position2:
    container: TenantSettingsTabs
    subcontainer: '3'
    height: 9.800000000000002
    width: 11
createdAt: 2021-11-11T08:30:58.011Z
