id: tailorConfigIndicator
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: left
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: >-
        {{!isTailorConfigInvalid.value ? "Config is Valid for upsert ✅" :
        "Config is Invalid for upsert⛔ ⛔"}}
    - _disclosedFields:
        array: []
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: TailorConfigForm
    rowGroup: footer
    row: 0.19999999999999996
    col: 6
    height: 0.6
    width: 2
createdAt: 2023-04-20T13:58:40.290Z
