id: TenantSettingsTabs
type: widget
subtype: ContainerWidget2
template:
  ordered:
    - _disabledByIndex:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - false
        - ''
        - ''
        - false
        - false
    - heightType: fixed
    - currentViewKey: 0
    - iconByIndex:
        array: []
    - clickable: false
    - _iconByIndex:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - bold/interface-alert-warning-triangle
    - hidden: null
    - showHeader: true
    - hoistFetching: true
    - views:
        array: []
    - showInEditor: null
    - tooltipText: ''
    - hiddenByIndex:
        array: []
    - _hiddenByIndex:
        - ''
        - false
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - false
        - ''
        - ''
        - false
        - false
    - _disclosedFields:
        array: []
    - currentViewIndex: 0
    - _hasMigratedNestedItems: true
    - transition: slide
    - itemMode: static
    - _tooltipByIndex:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
    - tooltipByIndex:
        array: []
    - showFooter: false
    - _viewKeys:
        - 0
        - '9'
        - '1'
        - 2
        - 3
        - 4
        - 5
        - 6
        - Cacher
        - 7
        - 8
        - '10'
        - Delete Tenant
    - events:
        - ordered:
            - event: change
            - type: datasource
            - method: trigger
            - pluginId: GetJobsConfig
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '200'
        - ordered:
            - event: change
            - type: datasource
            - method: trigger
            - pluginId: GetChosenDB2GraphConfig
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '200'
            - enabled: ''
        - ordered:
            - event: change
            - type: datasource
            - method: trigger
            - pluginId: GetJobs
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '200'
    - _ids:
        - '0'
        - cf8f8
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - 30cb7
        - '7'
        - '8'
        - 3c95f
        - '3e138'
    - viewKeys:
        array: []
    - iconPositionByIndex:
        array: []
    - _iconPositionByIndex:
        - ''
        - left
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - left
        - ''
        - ''
        - left
        - left
    - hovered: false
    - loading: false
    - overflowType: hidden
    - disabled: ''
    - _labels:
        - Tenant
        - TableFish
        - DB2Graph
        - Babelfish
        - Tailor
        - Argovisor
        - Sherlock
        - Metric-Tester
        - ''
        - Userator
        - Hermes
        - Tiny Tenant
        - ''
    - disabledByIndex:
        array: []
    - maintainSpaceWhenHidden: null
    - showBody: true
    - labels:
        array: []
style:
  ordered: []
position2:
  position2:
    container: tabs
    subcontainer: '8'
    height: 25.19999999999997
    width: 12
createdAt: 2021-11-12T07:45:35.449Z
