id: TenantSettingsForm
type: widget
subtype: FormWidget2
template:
  ordered:
    - disableSubmit: ''
    - heightType: fixed
    - resetAfterSubmit: false
    - submitting: false
    - hidden: null
    - data:
        object: {}
    - showHeader: false
    - hoistFetching: true
    - initialData: null
    - showInEditor: null
    - tooltipText: ''
    - _disclosedFields:
        array: []
    - invalid: false
    - showFooter: true
    - events:
        - ordered:
            - event: submit
            - type: datasource
            - method: trigger
            - pluginId: UpsertTenant
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
    - loading: ''
    - overflowType: hidden
    - disabled: ''
    - requireValidation: true
    - maintainSpaceWhenHidden: null
    - showBody: true
style:
  ordered: []
position2:
  position2:
    container: TenantSettingsTabs
    subcontainer: '0'
    height: 13.4
    width: 8
createdAt: 2021-10-27T23:07:47.130Z
