id: UpsertSherlockConfig
type: datasource
subtype: GraphQLQuery
resourceName: GraphQL-WithoutResource
template:
  ordered:
    - queryRefreshTime: ''
    - paginationLimit: ''
    - body: "mutation MyMutation($name: String , $config: jsonb, $schedule: String, $extra_params: jsonb) {\n\tinsert_jobs_one(object: {config: $config, name: $name}, on_conflict: {constraint: jobs_pkey, update_columns: config}) {\n    name\n  }\n  upsert_argo_cron(schedule: $schedule, workflow_type: $name, extra_params: $extra_params) {\n    msg\n  }\n}"
    - lastReceivedFromResourceAt: null
    - queryDisabledMessage: ''
    - servedFromCache: false
    - offlineUserQueryInputs: ''
    - successMessage: '{{UpsertSherlockConfig.data.upsert_argo_cron.msg}}'
    - queryDisabled: '{{isUnAuthorizedForUpsert.value}}'
    - playgroundQuerySaveId: latest
    - workflowParams: null
    - resourceNameOverride: ''
    - runWhenModelUpdates: false
    - paginationPaginationField: ''
    - headers: >-
        [{"key":"authorization","value":"Bearer
        {{tokenInput.value}}"},{"key":"x-role","value":"{{role.value}}"},{"key":"x-tenant-id","value":"{{tenantIdPicker.value}}"}]
    - showFailureToaster: true
    - paginationEnabled: false
    - query: https://api.{{stamp.value}}.sightfull.com/v1/graphql
    - playgroundQueryUuid: ''
    - playgroundQueryId: null
    - error: null
    - privateParams: []
    - runWhenPageLoadsDelay: ''
    - data: null
    - importedQueryInputs:
        ordered: []
    - isImported: false
    - graphQLVariables: >-
        [{"key":"name","value":"sherlock"},{"key":"config","value":"{{
        {configFilePath: SherlockTenantConfigPath.value}
        }}"},{"key":"schedule","value":"{{SherlockSchedule.value}}"},{"key":"extra_params","value":"{{
        {\"schemaRevision\": schemaRepoRevision.value } }}"}]
    - showSuccessToaster: true
    - cacheKeyTtl: ''
    - requestSentTimestamp: null
    - cookies: ''
    - metadata: null
    - queryRunTime: null
    - changesetObject: ''
    - errorTransformer: >-
        //Use the variables data, metadata, and errors to reference these fields
        from your query's results

        if (Array.isArray(errors) && errors.length > 0) {
          return errors[0].message;
        } else {
          return false
        }
            
    - finished: null
    - confirmationMessage: null
    - isFetching: false
    - changeset: ''
    - rawData: null
    - queryTriggerDelay: '0'
    - resourceTypeOverride: null
    - graphQLErrors: null
    - watchedParams: []
    - enableErrorTransformer: false
    - showLatestVersionUpdatedWarning: false
    - paginationDataField: ''
    - timestamp: 0
    - importedQueryDefaults:
        ordered: []
    - enableTransformer: true
    - showUpdateSetValueDynamicallyToggle: true
    - runWhenPageLoads: false
    - transformer: ''
    - events:
        - ordered:
            - event: success
            - type: datasource
            - method: trigger
            - pluginId: GetJobsConfig
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: success
            - type: widget
            - method: clear
            - pluginId: SherlockConfigForm
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: failure
            - type: widget
            - method: clear
            - pluginId: SherlockConfigForm
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: failure
            - type: datasource
            - method: trigger
            - pluginId: GetJobsConfig
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
    - queryTimeout: '10000'
    - workflowId: null
    - requireConfirmation: true
    - type: POST
    - queryFailureConditions: >-
        [{"condition":"{{metadata.status !=
        201}}","message":"{{UpsertSherlockConfig.data.upsert_argo_cron.msg}}"},{"condition":"","message":""}]
    - changesetIsObject: false
    - enableCaching: false
    - allowedGroups: []
    - bodyType: raw
    - offlineQueryType: None
    - queryThrottleTime: '750'
    - updateSetValueDynamically: false
    - notificationDuration: ''
createdAt: 2021-12-20T16:02:23.078Z
folder: Jobs
