id: UseratorConfigForm
type: widget
subtype: FormWidget2
template:
  ordered:
    - disableSubmit: '{{isUseratorConfigInvalid.value}}'
    - heightType: auto
    - resetAfterSubmit: ''
    - submitting: false
    - hidden: false
    - data:
        object: {}
    - showHeader: true
    - hoistFetching: true
    - _hasSubmitEvents: false
    - initialData: ''
    - showInEditor: false
    - tooltipText: ''
    - _disclosedFields:
        array: []
    - invalid: false
    - showFooter: true
    - events:
        - ordered:
            - event: submit
            - type: datasource
            - method: trigger
            - pluginId: UpsertUseratorConfig
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
            - enabled: '{{IsStaffRole.data && GetJobsConfig.data != undefined}}'
    - loading: false
    - overflowType: scroll
    - disabled: false
    - requireValidation: true
    - maintainSpaceWhenHidden: false
    - showBody: true
style:
  ordered: []
position2:
  position2:
    container: TenantSettingsTabs
    subcontainer: '7'
    row: 0.6000000000000014
    height: 5
    width: 12
createdAt: 2022-05-01T13:13:52.470Z
