id: button_saveFeedConfig
type: widget
subtype: ButtonWidget2
resourceName: null
template:
  ordered:
    - horizontalAlign: stretch
    - clickable: false
    - iconAfter: ''
    - submitTargetId: null
    - hidden: false
    - text: Save
    - showInEditor: false
    - tooltipText: ''
    - styleVariant: solid
    - submit: false
    - iconBefore: ''
    - events:
        - ordered:
            - event: click
            - type: datasource
            - method: trigger
            - pluginId: save_Config
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: click
            - type: widget
            - method: close
            - pluginId: modal_feedSetting
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
    - loading: false
    - loaderPosition: auto
    - disabled: false
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    row: 11.8
    col: 1
    height: 1
    width: 1
createdAt: 2022-01-29T03:04:58.193Z
