version: 43.0.9
pageUuid: e3b8fe70-fca9-11ec-95f0-bbd5319ce9e9
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.95.0
