version: 43.0.9
pageUuid: 16ebb154-b211-11ec-826e-6385b57aacf7
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.103.7
  markdownLinkBehavior: auto
  experimentalStabilityFeatures:
    object:
      lockModelForUpdates: true
