version: 43.0.9
pageUuid: 3aa2a8ff-b241-4cf2-b7e1-5c464a64df90
appTemplate:
  appThemeId: 17
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.107.10
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
