version: 43.0.9
pageUuid: bd38178a-0fed-11ec-a16c-a3ccebb4527e
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.94.5
