id: planConfigurationModule2
type: widget
subtype: GlobalWidget
template:
  ordered:
    - heightType: auto
    - dependentCoverage: '{{dependentCoverage.value}}'
    - gracePeriodEnabled: '{{gracePeriodEnabled.value}}'
    - showFetchingIndicator: boolean
    - pageUuid: 5307d707-7aa6-4939-bd5a-269de4a88f7c
    - rolloverType: '{{rolloverType.value}}'
    - name: planConfigurationModule
    - rolloverEnabled: '{{rolloverEnabled.value}}'
    - planName: ''
    - autoAdjudication: '{{autoAdjudication.value}}'
    - balanceAvailability: '{{balanceAvailability.value}}'
    - productName: '{{productName.value}}'
    - terminatedRunoutEnabled: '{{terminatedRunoutEnabled.value}}'
    - runoutEnabled: '{{runoutEnabled.value}}'
    - childNamespace: planConfigurationModule2
style:
  ordered: []
position2:
  position2:
    col: 8
    height: 2.4
    width: 2
createdAt: 2023-08-21T18:36:22.585Z
