version: 43.0.9
pageUuid: 3366f962-3639-11ee-8e44-c74d47c350ef
appTemplate:
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  version: 3.4.2
  experimentalDataTabEnabled: true
