version: 43.0.9
pageUuid: 1a9b9b90-722b-11ed-85f6-df98d11a432f
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  queryStatusVisibility: true
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  isFetching: true
  version: 3.4.2
  markdownLinkBehavior: never
