mutation UnpinSignalFromEverywhere($signal_id: uuid!) {
  delete_feed_signals(where: {signal_id: {_eq: $signal_id}}) {
    returning {
      feed {
        user {
          email
        }
        workspace {
          name
        }
      }
    }
    affected_rows
  }
}