mutation UpsertDetection(
  $config: jsonb
  $display_name: String!
  $execution_options: jsonb!
  $id: String!
  $require_oversight: Boolean!
  $schedule: String!
  $state: jsonb!
  $timeout_seconds: Int
  $type: String!
) {
  insert_detections_one(
    object: {
      config: $config
      display_name: $display_name
      execution_options: $execution_options
      id: $id
      require_oversight: $require_oversight
      schedule: $schedule
      state: $state
      timeout_seconds: $timeout_seconds
      type: $type
    }
    on_conflict: {
      constraint: detections_pkey
      update_columns: [
        display_name,
        execution_options,
        require_oversight,
        config,
        schedule,
        type
      ]
    }
  ) {
    display_name
  }
}
