version: 43.0.9
pageUuid: 5307d707-7aa6-4939-bd5a-269de4a88f7c
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  isGlobalWidget: true
  version: 2.123.1
  experimentalDataTabEnabled: true
