id: product
type: widget
subtype: TextInputWidget2
template:
  ordered:
    - spellCheck: false
    - readOnly: 'true'
    - iconAfter: ''
    - showCharacterCount: false
    - autoComplete: false
    - maxLength: null
    - hidden: false
    - customValidation: ''
    - patternType: ''
    - hideValidationMessage: false
    - textBefore: ''
    - validationMessage: ''
    - textAfter: ''
    - showInEditor: false
    - showClear: false
    - pattern: ''
    - tooltipText: ''
    - labelAlign: left
    - formDataKey: '{{ self.id }}'
    - value: '{{ getproductid.data }}'
    - labelCaption: ''
    - labelWidth: '15'
    - autoFill: ''
    - placeholder: ''
    - label: 'Product:'
    - _validate: false
    - labelWidthUnit: '%'
    - invalid: false
    - iconBefore: ''
    - minLength: null
    - inputTooltip: ''
    - events:
        ordered: []
    - autoCapitalize: none
    - loading: false
    - disabled: false
    - labelPosition: left
    - labelWrap: false
    - maintainSpaceWhenHidden: false
    - required: false
style:
  ordered: []
position2:
  position2:
    container: container3
    subcontainer: 09a1c
    col: 5
    height: 1
    width: 3
createdAt: 2023-02-08T20:18:21.837Z
