id: ProductSelect
type: widget
subtype: SelectWidget2
template:
  ordered:
    - imageByIndex:
        array: []
    - _disabledByIndex: []
    - showSelectionIndicator: true
    - _values: []
    - iconByIndex:
        array: []
    - values: '{{ item.processingOrder.processingOrderId }}'
    - readOnly: false
    - iconAfter: ''
    - _iconByIndex: []
    - overlayMinWidth: null
    - allowDeselect: false
    - inputValue: ''
    - hidden: false
    - customValidation: ''
    - data: '{{ productsQuery.data }}'
    - searchMode: fuzzy
    - hideValidationMessage: false
    - fallbackTextByIndex:
        array: []
    - textBefore: ''
    - _fallbackTextByIndex: []
    - selectedItem: null
    - validationMessage: ''
    - automaticItemColors: false
    - itemAdornmentShape: circle
    - textAfter: ''
    - showInEditor: false
    - showClear: false
    - tooltipText: ''
    - labelAlign: left
    - formDataKey: '{{ self.id }}'
    - value: null
    - hiddenByIndex:
        array: []
    - labelCaption: ''
    - labelWidth: '33'
    - deprecatedLabels:
        array: []
    - _hiddenByIndex: []
    - placeholder: Select an option
    - _captionByIndex: []
    - itemAdornmentSize: auto
    - label: 'Products:'
    - _hasMigratedNestedItems: true
    - captionByIndex: '{{ item.processingOrder.processingOrderId }}'
    - _validate: false
    - itemMode: dynamic
    - labelWidthUnit: '%'
    - allowCustomValue: false
    - invalid: false
    - selectedIndex: null
    - _tooltipByIndex: []
    - _colorByIndex: []
    - tooltipByIndex:
        array: []
    - iconBefore: ''
    - colorByIndex:
        array: []
    - selectedLabel: ''
    - events:
        - ordered:
            - event: change
            - type: script
            - method: run
            - pluginId: ''
            - targetId: null
            - params:
                ordered:
                  - src: Window.procNum = {{ProductSelect.value}};
            - waitType: debounce
            - waitMs: '0'
    - _ids: []
    - emptyMessage: ''
    - overlayMaxHeight: 375
    - loading: false
    - disabled: false
    - labelPosition: left
    - _labels: []
    - labelWrap: false
    - disabledValues:
        array: []
    - disabledByIndex:
        array: []
    - maintainSpaceWhenHidden: false
    - _imageByIndex: []
    - required: false
    - labels: '{{ item.productName }}'
style:
  ordered: []
position2:
  position2:
    container: container2
    subcontainer: 2bb74
    row: 1
    height: 1
    width: 12
createdAt: 2022-12-21T17:07:01.987Z
