version: 43.0.9
pageUuid: 979f9258-d30c-11ed-8d72-afa63cb40f79
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
      displaySetting:
        object:
          landscapeMode: false
          tabletMode: false
  preloadedAppJavaScript: |-
    window.formatPhoneNumber = function(value) {
      if (!value) return value;
      const phoneNumber = value.replace(/[^\d]/g, '');
      const phoneNumberLength = phoneNumber.length;
      if (phoneNumberLength < 4) return phoneNumber;
      if (phoneNumberLength < 7) {
        return `(${phoneNumber.slice(0, 3)}) ${phoneNumber.slice(3)}`;
      }
      return `(${phoneNumber.slice(0, 3)}) ${phoneNumber.slice(3,6)}-${phoneNumber.slice(6, 10)}`;
    }
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  preloadedAppJSLinks:
    array:
      - https://cdn.jsdelivr.net/npm/graphql-request@6.0.0/+esm
  version: 3.0.1
  experimentalDataTabEnabled: true
