version: 43.0.9
pageUuid: 29459f20-e513-11eb-991a-e34948acca2f
appTemplate:
  appStyles: |-
    .ph16 > div:first-child > button > span {
      display: none;
    }

    .ph16 > div:first-child > button::after {
      content: "Reiniciar"
    }

    .ph16 > div:last-child > button > span {
      display: none;
    }

    .ph16 > div:last-child > button::after {
      content: "Retroceder"
    }
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
  rootScreen: null
  version: 2.89.1
