id: frmApplicationInfo
type: widget
subtype: FormWidget2
template:
  ordered:
    - disableSubmit: false
    - heightType: auto
    - resetAfterSubmit: true
    - submitting: false
    - hidden: false
    - data:
        object: {}
    - showHeader: true
    - hoistFetching: true
    - initialData: |2-
          {
            "startup_name": {{GET_ApplicationInfo_.data.startup_name}},
            "legal_name": {{GET_ApplicationInfo_.data.legal_name}},
            "hq": {{GET_ApplicationInfo_.data.hq}},
                "street_address_input": {{ 
                    GET_ApplicationInfo_.data.street_address }},
                  "country":{{GET_ApplicationInfo_.data.country}},
                    "state":{{GET_ApplicationInfo_.data.state}},
                      "city":{{GET_ApplicationInfo_.data.city}},
                        "postal_code":{{GET_ApplicationInfo_.data.postal_code}},
               "website": {{GET_ApplicationInfo_.data.website}},
              "anticipated_spend": {{GET_ApplicationInfo_.data.anticipated_spend}},
              "industry": {{GET_ListIndustries.data.industries_info.find(industru => industru.name == GET_ApplicationInfo_.data.industry).id }},
              "rfc": {{GET_ApplicationInfo_.data.rfc}}
          }
    - showInEditor: false
    - tooltipText: ''
    - invalid: false
    - showFooter: true
    - events:
        - ordered:
            - event: submit
            - type: datasource
            - method: trigger
            - pluginId: prepareEditApplicantData
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
    - loading: ''
    - overflowType: scroll
    - disabled: false
    - requireValidation: true
    - maintainSpaceWhenHidden: false
    - showBody: true
style:
  ordered: []
position2:
  position2:
    container: Company_tbdCntr
    subcontainer: 78cc3
    row: 0.19999999999999996
    height: 18.4
    width: 12
createdAt: 2022-05-19T01:13:54.250Z
