version: 43.0.9
pageUuid: 8d6ed570-e391-11ec-bfd2-97208cc993bf
appTemplate:
  preloadedAppJavaScript: |-
    window.myFunction = () => {
      console.log('testing');
      return false;
    }
  rootScreen: null
  isGlobalWidget: true
  version: 2.90.12
  markdownLinkBehavior: auto
